workflows:
  ytbuild:
    name: YTLitePlus Build
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      xcode: latest

    scripts:
      - name: Clean
        script: |
          git submodule deinit -f .
          git clean -fdx

      - name: Init submodules
        script: |
          git submodule update --init --recursive --depth 1

      - name: Build
        script: |
          chmod +x build.sh
          ./build.sh

    artifacts:
      - packages/*.ipa
